name: Build application and store it on the deployment service
on:
  push:
    tags:
      - 'v*'
      - 'v*-staging'
      - 'v*-stable'

jobs:
  build:
    env:
      ACTIONS_STEP_DEBUG: true
      COMPOSER_HOME: ~/.composer
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v2
        with:
          # Optionally strip `v` prefix
          strip_v: true
      - name: Copy production composer
        run: cp production.composer.json composer.json
      - name: Remove composer.lock
        run: rm composer.lock -f
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --ignore-platform-req=ext-xmlwriter --ignore-platform-req=ext-simplexml --ignore-platform-req=ext-xml --ignore-platform-req=ext-dom
      - name: Pack the application
        run: sudo docker build -t registry.plusclouds.com/leo4-ai-assistance:${{steps.tag.outputs.tag}} -t registry.plusclouds.com/leo4-domain-validator:latest -t registry.plusclouds.com/leo4-domain-validator .
      - name: Pushing to registry
        run: docker image push --all-tags registry.plusclouds.com/leo4-domain-validator
